name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Build
      run: go build -o build/helloapp

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: helloapp
        path: build/helloapp